### PR TITLE
Add drone (arm) update cirrus (freebsd) update badges

### PR DESCRIPTION
**Pull request by IanButterworth**
Hoping to root out the problem causing https://github.com/JuliaIO/FileIO.jl/issues/236

### CODE REVIEW

**Comment by IanButterworth** [comment]
The ARMv7 (drone) issue is https://github.com/JuliaLang/julia/issues/32257
The AARCH64 error seemed to be a failed download (restarted)

The FreeBSD (cirrus) issue does seem to be something more

**Comment by IanButterworth** [comment]
I'm guessing this is a problem with ImageMagickBuilder on FreeBSD

Any ideas @giordano?

**Comment by giordano** [comment]
No clue, but it may be worth using binaries in JuliaBinaryWrappers: https://cirrus-ci.com/build/5421907714768896 (this is the commit tested: https://github.com/giordano/ImageMagick.jl/commit/5bb57f57b0deded6eac53e4e76a1fe857b1f3b8d)

**Comment by IanButterworth** [comment]
FreeBSD definitely has failures, but I can't get it to replicate the ```NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/560``` error seen over in [YOLO.jl](https://cirrus-ci.com/task/5554952706981888?command=test#L11)


cc @SimonDanisch

**Comment by timholy** [comment]
This might need rebasing

**Comment by IanButterworth** [comment]
Stale

**Pull request closed without merging**
