### PR TITLE
Improve support for writing images with transparency (fixes Images#396)

### PR DESCRIPTION
**Pull request by timholy**
Fixes https://github.com/timholy/Images.jl/issues/396

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, Homebrew error. I'm not going to let that hold this up, and I'll merge once AppVeyor passes. But anyone have any ideas about how to fix?

**Comment by SimonDanisch** [comment]
``` Julia
INFO: Building ImageMagick
Error: Tap staticfloat/juliadeps already tapped.
```

@staticfloat might know more?

**Comment by timholy** [comment]
Amazing we hadn't detected this problem before, definitely needed fixing. Not how I had hoped to spend my morning, however :disappointed:.

**Comment by SimonDanisch** [comment]
So this was fine in this PR on Appveyor, but fails when merged into master?

**Comment by timholy** [comment]
1/4 and not related to this PR. This looks like the problem that 16a9226e1e2704b985dc566a5d5a779fde2b44af was designed to fix, I don't understand why it's happening again.

**Comment by timholy** [comment]
Maybe we need to write a few more pixels---perhaps IM is trying to be really clever, and if all `UInt`-representable values are evenly divisible by 4 it uses a smaller bit depth. Honestly, I just wish IM would do the obvious thing.

**Pull request merged**
