### PR TITLE
Only call genesis if not already instantiated

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
`IsMagickInstantiated`  got renamed to   `IsMagickWandInstantiated` within the same version major `0.6`  argggg 

I'm having great difficulty in finding the exact doc on when this changed  so I can version this call.

**Comment by musm** [comment]
I'm a little confused,so I'm trying to make sure BinDeps is installing the latest Imagemagick library files. Looking at https://packages.debian.org/jessie/libmagickwand-6.q16-2 it says that the library version is 6.8.9.9-5 yet when checking the library version from ImageMagick.jl it get's version 6.6.9.

Now is `BinDeps` ignoring downloading the package since it detects an already installed version on the host system? ... that's my hunch

Might be better to do a custom BinDeps  install from source? ( @timholy opinions regarding this latter point)

**Comment by timholy** [comment]
> IsMagickInstantiated got renamed to IsMagickWandInstantiated within the same version major 0.6 

Oh, wow, that's...incredible. One thought is to call `Libdl.dlsym` and see which version can be resolved.

> Might be better to do a custom BinDeps install from source? ( @timholy opinions regarding this latter point)

What's the build time like? Keep in mind that ImageMagick.jl gets used for Travis tests on quite a few packages; if building ImageMagick takes 15 minutes, that's extra time added to each `git push`. OTOH if it builds in a minute or so then I think it's no problem.

**Comment by musm** [comment]
Good point. The build times are less than 15 mins, maybe around ~2-5 ish. 
I think I will use  custom versioning for now, since  I believe it's in versions less than 6.9 that are using `IsMagickInstantiated` 

latest commit should fix travis

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
