### PR TITLE
Update version and ImageMagick_jll compat to work on Mac M1

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by johnnychen94** [comment]
Unfortunately this ImageMagick_jll version is broken... which is why I rolled it back to v6.9.10 in https://github.com/JuliaIO/ImageMagick.jl/pull/207

**Comment by asinghvi17** [comment]
Just saw that issue - whoops :) guess I should close this for the time being then.  Unfortunately it seems like v6.9.10 does not have a build for Mac M1 - do you know if it's possible to retroactively add one?

**Comment by johnnychen94** [comment]
@giordano is it possible to rebuild the v6.9.10 version with M1 enabled? Maybe revert the recipe commit in the Yggdrasil since we know that is a broken version?

**Comment by giordano** [comment]
Not keeping the same version number, it'd wreak havoc in older versions of Julia: https://github.com/JuliaPackaging/Yggdrasil/issues/2763

**Pull request closed without merging**
