### PR TITLE
on OS X use homebrew's just released imagemagick@6

### LINKED ISSUE #57: homebrew imagemagick updated to 7.0.4
i think this update just happened last night.  IIRC there are API changes in imagemagick 7 that would require substantial changes to imagemagick.jl to support.  if true, it seems in the short term we should perhaps modify the build script, again, to have homebrew install the last 6.9 imagemagick version instead.  anyone know how to do this?

### PR DESCRIPTION
**Pull request by bjarthur**
closes https://github.com/JuliaIO/ImageMagick.jl/issues/57

@samuelpowell could you please test if this works for you?

### CODE REVIEW

**Comment by samuelpowell** [comment]
@bjarthur remarkably, it segfaults Julia!

```
julia> Homebrew.unlink("ImageMagick")
Unlinking /Users/spowell/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick/7.0.4-4... 71 symlinks removed

julia> include("build.jl")
WARNING: Method definition library_group(Any...) in module Main at /Users/spowell/.julia/v0.5/BinDeps/src/dependencies.jl:85 overwritten at /Users/spowell/.julia/v0.5/BinDeps/src/dependencies.jl:85.
WARNING: Method definition library_dependency(Any...) in module Main at /Users/spowell/.julia/v0.5/BinDeps/src/dependencies.jl:86 overwritten at /Users/spowell/.julia/v0.5/BinDeps/src/dependencies.jl:86.
WARNING: Method definition #library_dependency(Array{Any, 1}, Main.#library_dependency, Any...) in module Main overwritten.
==> Installing imagemagick@6 from staticfloat/juliatranslated
==> Downloading https://juliabottles.s3.amazonaws.com/imagemagick@6-6.9.7-3.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring imagemagick@6-6.9.7-3.sierra.bottle.tar.gz
🍺  /Users/spowell/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick@6/6.9.7-3: 1,464 files, 22.2M
Warning: Already linked: /Users/spowell/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick@6/6.9.7-3

signal (11): Segmentation fault: 11
while loading /Users/spowell/Documents/ImageMagick.jl/deps/build.jl, in expression starting on line 125
MagickQueryConfigureOption at /Users/spowell/.julia/v0.5/Homebrew/deps/usr/lib/libMagickWand-6.Q16.dylib (unknown line)
anonymous at ./<missing> (unknown line)
unknown function (ip: 0x316a80941)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:569
jl_eval_module_expr at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:196
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:465
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/ast.c:717
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:596 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20125 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
do_call at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:66
eval at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:190
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:558
jl_toplevel_eval_in_warn at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/builtins.c:590
eval at ./boot.jl:234
jlcall_eval_19752 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
eval_user_input at ./REPL.jl:64
unknown function (ip: 0x316a19566)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:68
unknown function (ip: 0x316a160df)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1392 [inlined]
start_task at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:253
Allocations: 6233455 (Pool: 6232114; Big: 1341); GC: 9
Segmentation fault: 11
```

**Comment by bjarthur** [comment]
i think the proper procedure is:

```
Homebrew.rm("imagemagick")
Pkg.build("ImageMagick")
```

if that doesn't work, go nuclear:  `rm -rf .julia/v0.5`

**Comment by bjarthur** [comment]
hmmm...  just noticed the OS X builds are failing.  i'll look into it....

**Comment by samuelpowell** [comment]
Okay, ping me if you'd like me to try again.

**Comment by bjarthur** [comment]
@staticfloat Homebrew.jl returns an incorrect version suffix which is the cause of @samuelpowell 's error above i believe.


```
julia> Homebrew.prefix("imagemagick@6")
"/Users/arthurb/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick@6/6.9.7-4"
```

it should be `-3` to match the version installed according to the log trace.

this is breaking for both `staticfloat/juliadeps/imagemagick@6` and just `imagemagick@6`.  do you know where the likely bug is?  thanks.

**Comment by staticfloat** [comment]
@bjarthur because `imagemagick@6` is provided both by my tap, and by another, it's ambiguous as to whether you intend to install my tap's version (which is `-3`) or the other version (which is `-4`).  So always fully-qualify your names:

```
julia> Homebrew.prefix("imagemagick@6")
"/Users/sabae/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick@6/6.9.7-4"

julia> Homebrew.prefix("staticfloat/juliadeps/imagemagick@6")
"/Users/sabae/.julia/v0.5/Homebrew/deps/usr/Cellar/imagemagick@6/6.9.7-3"
```

Yes, this is an annoying inconsistency, but you should definitely fully-qualify your formula names.

**Comment by bjarthur** [comment]
thanks @staticfloat for teaching me a bit more about homebrew.

the problem then seems to be that `ImageMagick/deps/build.jl`, though it specifies `imagemagick@6` in this PR, is installing the -3 version from staticfloat/juliadeps.  see the only change in this PR, and the travis logs.  any idea?

**Comment by staticfloat** [comment]
Try putting `homebrew/core/imagemagick@6`, that's how you fully-qualify a "normal" homebrew formula name.  I will eventually remove the `imagemagick@6` formula from my tap, but I'd like to make sure this actually works first.

**Comment by bjarthur** [comment]
tests are passing!  thanks @staticfloat 

@samuelpowell please try again

**Comment by samuelpowell** [comment]
@bjarthur this works fine and all tests pass.

Please note that I was forced to delete my Julia package directory - attempting to build the package without doing so caused a recurrence of the error I reported previously (using `Homebrew.rm("ImageMagick") did not suffice for me).

Thank you for your efforts!

**Pull request merged**
