### PR TITLE
Validate provider's library versions during build

### PR DESCRIPTION
**Pull request by musm**
Since we do not support imagemagick 7

### CODE REVIEW

**Comment by musm** [comment]
not sure why I thought this would work on osx....

**Comment by Allardvm** [comment]
I'll take a look at this today. Must be a pain to work on this without access to a mac, considering how fragile the package is on osx.

**Comment by Allardvm** [comment]
This turns out to be quite tricky. ImageMagick gets all of these QueryOptions from `configure.xml`, which it tries to locate with (amongst others) `ENV["MAGICK_CONFIGURE_PATH"]`. If it can't find it, we run into a segfault. So we'll have to set this environment variable before we call the QueryOptions, but BinDeps doesn't call a provider's `preload` or `onload` during the validation call—so we'll have to find another way to set `MAGICK_CONFIGURE_PATH`.

Note that we cannot just set the path when we define the Homebrew provider, since BinDeps could find a system-wide installation of ImageMagick with `configure.xml` in one of the paths that ImageMagick looks for automatically, namely (for version 7):

```
$MAGICK_CONFIGURE_PATH
$MAGICK_HOME/etc/ImageMagick-7 
$MAGICK_HOME/share/ImageMagick-7 
$PREFIX/share/ImageMagick-7 
$XDG_CACHE_HOME/ImageMagick
$HOME/.config/ImageMagick/
<client path>/etc/ImageMagick
<current directory>
```
Had we set `MAGICK_CONFIGURE_PATH` to the Homebrew installation, then the system-wide install would try to load `configure.xml` from the Homebrew installation and would report the wrong version—and possibly trip over other stuff.

_Update: I've modified the code to detect when BinDeps checks a provider that needs ENV to be set so that we can set it. The commit also instantiates and terminates MagickWand during the version check._

**Comment by musm** [comment]
wow great thanks.. are you positive we actually need to  instantiate and terminate MagickWand for the version test? During my tests it was not necessary.

**Comment by musm** [comment]
We should probably also just call this in the `libmagic.jl` file since it should work outside the `__init__` function now. That way we can avoid the runtime version check.

**Comment by Allardvm** [comment]
The ImageMagick documentation suggests that Genesis and Terminus should always be called. I couldn't find any definitive info on whether it's also required for just retrieving the version number and a cursory check of the source code didn't help either. However, this [post](http://www.imagemagick.org/discourse-server/viewtopic.php?t=8243) suggests that, if Genesis/Terminus aren't used, the environment is terminated as soon as the number of wands reaches zero. This is fine while building, and is consistent with the passing tests, so let's omit the calls to Genesis and Terminus.

As for checking the version number during recompilation or at runtime: I would prefer runtime. We need to instantiate the MagickWand environment anyway, and the call to get the version takes an insignificant amount of time, so there is very little downside to runtime. On the upside, runtime will ensure that libversion is always up-to-date, which is more intuitive, will make debugging easier, and allows us to rely on it in code that needs to differ between versions. I'd prefer to update the version number in a top-level defined `const _libversion = Ref{VersionNumber}()`  during the call to `__init()__`, and exposing it with a function `libversion() = _libversion[]`. This should be amenable to precompilation, and is type stable.

As a last point, note that checking whether the MagickWand is instantiated before calling Genesis isn't necessary because MagickWand already takes care of this (see https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/magick-wand.c#L1001). I propose that we merge the changes in this PR over those in https://github.com/JuliaIO/ImageMagick.jl/pull/95.

To avoid conflicting commits, could you make these changes if you agree with the above? If you'd rather have me do it, let me know.

**Comment by musm** [comment]
Sounds good. Thanks for the detailed reply and please go ahead with the changes.

Regarding the runtime or not, I'm fine with your suggestions.

**Comment by musm** [comment]
so should we merge this?

**Comment by musm** [comment]
Also any objections to doing a squash merge?

**Comment by Allardvm** [comment]
This is ready to merge as far as I'm concerned. I was indeed intending to squash it. @timholy, any objections/suggestions?

**Comment by timholy** [comment]
You folks are much better informed than I am about all these platform/library issues than I, but I didn't see anything to complain about. Go for it.

**Pull request merged**
