### PR TITLE
A compat release for older versions of Julia

### PR DESCRIPTION
**Pull request by timholy**
xref https://github.com/JuliaRegistries/General/pull/11114

### CODE REVIEW

**Comment by johnnychen94** [comment]
IMO it would be better to not depend on colortypes and fixedpointnumbers and set ImageCore to `0.8.1`

Seems that ImageMagick doesn't have a CompatHelper yet

Cref: https://github.com/JuliaIO/QuartzImageIO.jl/pull/66

**Comment by timholy** [comment]
Yeah, good idea, that's better than just modernizing the existing dependencies.

**Comment by timholy** [comment]
Since this will affect tests in many packages, i'll merge this tomorrow unless objections emerge.

**Review by johnnychen94 — APPROVED** [review]

**Comment by johnnychen94** [comment]
compat helper added in #187

**Pull request merged**
