### PR TITLE
fixing UFixed deprecations

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by yuyichao** [comment]
Should bump julia version requirement and remove CI for 0.3 since FixedPointNumbers 0.1.0 is 0.4+ only.

**Comment by yuyichao** [comment]
Also need to bump FixedPointNumbers version requirement of course...

**Comment by timholy** [comment]
I was planning to tackle getting this merged and got derailed by https://github.com/JuliaLang/julia/pull/13809. It's a really bad bug, and much more exposed now that the new FixedPointNumbers uses the same promotion rules as julia 0.4.

**Comment by timholy** [comment]
Incorporated into #14.

**Pull request merged**
