### PR TITLE
Switch to new FileIO organization, add writing

### PR DESCRIPTION
**Pull request by timholy**
I haven't added any tests yet for this, so I have no idea whether it works. But I thought I'd push this early to avoid duplication of work.

### CODE REVIEW

**Comment by timholy** [comment]
See https://github.com/SimonDanisch/ColorTypes.jl/pull/1

**Comment by SimonDanisch** [comment]
Okay I call it a day for now... I will see if I can fix up Images.jl tomorrow and then test it with my image tests in GLVisualize!

**Comment by timholy** [comment]
This is great. Thanks for pushing to this branch, I can try to play a little more with it myself if I get some time.

**Comment by SimonDanisch** [comment]
I will merge this for now, since it seems mostly functional.
The problems still lay in the detail.
There are some differences between what e.g. `Images.grayim` and `load("grayim")` produces.
Then there seem to be problems with permuted dims, where I don't really know who correctly permutes them.
I also don't really understand what problems `mapinfo` really solves. It seems to be overcomplicated, but then again I haven't implemented it and don't know all the problems and corner cases it solves.
But it seems it's working for now, even though I don't fully understand it :D 
Also, it's not fully clear, what should stay in Images and what should stay in ImageMagick.

**Comment by timholy** [comment]
Sorry I haven't had time to look at this. I'll try to get to it later today.

**Comment by SimonDanisch** [comment]
No worries! It's good that I get familiar with the code ;)

**Pull request merged**
