### PR TITLE
Fix depwarn of readall in deps/build.jl

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
The failure looks like a legitimate issue but is unrelated to this PR?

**Comment by timholy** [comment]
Oops, looks like I broke something. I should get in the habit of running the ImageMagick tests whenever I make changes to Images. (In fact, perhaps this would be good to set up on Travis.)

**Comment by yuyichao** [comment]
Hmm, I assume you didn't mean to close the PR?

**Comment by timholy** [comment]
Yeah, that was an auto-close.

Nice that it's passing Travis on 0.4 now. Merge when ready.

**Pull request merged**
