### PR TITLE
Added writeimage(::MagickWand, ::IO) method

### PR DESCRIPTION
**Pull request by sglyon**
Added a method to write an image to an IO stream instead of just a filename

### CODE REVIEW

**Comment by timholy** [comment]
Can this have a test?

**Comment by sglyon** [comment]
I was trying to decide how. What if I read in a file, then write it out
again using this method?  That doesn't really check for correctness, we'd
just be relying on the c function to be correct

// Spencer

**Comment by sglyon** [comment]
OK I have added a test for the new method introduced here. 

I'm not sure why the tests for reading from streams had `@unix_only` in front of them, but I figured if they had issues there I probably would too so I left it in.

Also I'm relying on `==(::Image, ::Image)` being a valid way to test that the new image I wrote out is the same as the one I read in. I'm not sure if that is a safe assumption to make.

**Comment by tbreloff** [comment]
@spencerlyon2 You may be interested in https://github.com/tbreloff/VisualRegressionTests.jl which forms the basis of the Plots regression testing.  This is based on the image comparison method created by @timholy.

(I came here because I want to merge/test your "Plotsly" PR :)

**Comment by timholy** [comment]
Note the travis failure seems to have a different cause, however.

**Comment by timholy** [comment]
See #29.

**Comment by sglyon** [comment]
Thanks! I’ll take a look at #29

// Spencer

On February 27, 2016 at 10:00:56 AM, Tim Holy (notifications@github.com) wrote:

See #29.

**Pull request closed without merging**
