### PR TITLE
Update to ImageMagick 7 library that almost works.

### LINKED ISSUE #232: Update to ImageMagick 7.1
ImageMagick 7.1 is now in Yggdrasil. https://github.com/JuliaRegistries/General/pull/105903. Would be nice to get this package to upgrade. I imagine the upgrade may not be easy or straightforward, and hence opening this issue to see if someone might be interested in trying it out and seeing what it takes.

### PR DESCRIPTION
**Pull request by dgleich**
Fixes #232 

But this still causes the issue with #206. I'm not quite sure how that one got changed, but it seems like it was another issue outside of the core library. So I'm starting this pull request to debug further. 

This also bumps the version number to 1.4.0 because there could be other things that change with the version 7 library. 

Do we want to add webp support as part of this too?

### CODE REVIEW

**Comment by dgleich** [comment]
This also 

Fixes #231

**Comment by dgleich** [comment]
Does anyone know how #206 was fixed? Just by reverting the library? The issue seems like it's some odd interaction with libtiff.

**Comment by dgleich** [comment]
Here are relevant links:

 - https://gitlab.com/libtiff/libtiff/-/issues/532

**Comment by dgleich** [comment]
(Apologies -- not sure how I closed it.)

**Comment by timholy** [comment]
Yes, I think we reverted it.

**Comment by ViralBShah** [comment]
@dgleich Gave you commit access here (in case it helps).

**Comment by dgleich** [comment]
Okay, the latest update (which was pushed to master directly...) fixes the tiff issue by ignoring the tags. This passes on cameraman, which was one of the files blocked last time. It also introduces the original PNG test from issue 206, which passes. 

I should probably update the readme to mention that it's now ImageMagick 7 instead of ImageMagick 6... 

@ViralBShah @timholy any other checks you or others would like to see? (Just a reminder this bumps the version to 1.4.0...)

**Comment by ViralBShah** [comment]
My main interest was to see Imagemagick updated and working again (even if we disable a couple of things). I am not a major user of this package otherwise.

I believe folks here will prefer working with branches and merging when CI is green.

**Comment by ViralBShah** [comment]
The other nice thing to fix would be this warning:

```
┌ ImageMagick
│  WARNING: using deprecated binding Colors.RGB1 in ImageCore.
│  , use XRGB instead.
│  WARNING: using deprecated binding Colors.RGB4 in ImageCore.
│  , use RGBX instead.
└  
```

I suppose we should close this PR for now?

**Pull request closed without merging**
