### PR TITLE
Update build.jl

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by bjarthur** [comment]
wow, so am i to infer that ImageMagick has never worked on windows for julia 0.5 ?

**Comment by timholy** [comment]
AppVeyor says it has been, but presumably this eliminates a depwarn that we never noticed?

**Comment by timholy** [comment]
Thanks, @musm!

**Comment by musm** [comment]
It used to work, but stopped when dropping 0.4 and `Compat`

**Pull request merged**
